import type { Metadata } from "next";
import { Bodoni_Moda_SC, Raleway} from "next/font/google";
import "./globals.css";
import Nav from "../../components/nav";
import Footer from "../../components/footer";

const bodoniModaSC = Bodoni_Moda_SC({
  variable: "--font-bodoni-moda-sc",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Nav />
      <body
        className={`${bodoniModaSC.variable} ${raleway.variable} antialiased`}
      >
        {children}
      </body>
      <Footer />
    </html>
  );
}
