import type { Metadata } from "next";
import { Bodoni_Moda_SC, Raleway} from "next/font/google";
import "./globals.css";
import Nav from "../../components/nav";

const bodoniModaSC = Bodoni_Moda_SC({
  variable: "--font-bodoni-moda-sc",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overfolow-x-hidden overflow-y-scroll">
      <Nav />
      <body
        className={`${bodoniModaSC.variable} ${raleway.variable} antialiased`}
      >
        {children}
      </body>
      <div className="lg:h-100 h-50 w-full bg-cover bg-center bg-[url('../../photos/mountain-road-paint.jpg')] py-0">
        <div className="h-full w-full bg-gradient-to-b from-sky-200 to-slate-200/0"> 
        </div>
      </div>
    </html>
  );
}
